import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: 'welcome to next.js 15',
    template: `%s | Next.js 15`,
  },
  description: "Generated by create next app",
};

const navigations =[ 
  { title: 'About', href: '/about'},
  { title: 'contact', href: '/contact'},
  { title: 'blog', href: '/blog'},
  { title: 'products', href: '/products'},
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathName = '/about';

  return (
    <html lang="en" data-theme='light'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-3.5 bg-orange-600 font-semibold">
         {navigations.map((nav)=> {
         const isActive = pathName === nav.href || (pathName.startsWith(nav.href) && nav.href)
          return (
          <Link className="mr-4 font-black" key={nav.title} href={nav.href}>{nav.title}</Link>)
          })}
        </div>
        {children}
      </body>
    </html>
  );
}
